services:
  - type: web
    name: chuck-lash
    env: node
    plan: free
    branch: master
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: HOST_PIN
        sync: false
      - key: ROOM_CODE
        value: CHUCK
